# Generated by Django 3.2.13 on 2022-12-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221228_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
